### ISSUE TITLE
Black screen when switching to nvidia.

### ISSUE THREAD

**Issue by LouisHLAV** [dglt1/optimus-switch-sddm#11]
Hi! I just installed optimus-switch following the instructions in the readme page and it works just fine for intel mode:
`inxi -g` returns
```
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Display: x11 server: X.Org 1.20.8 driver: intel
  resolution: 2160x1440~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2)
  v: 4.6 Mesa 20.0.4
```
The problem arises when I try to use nvidia mode, which causes a black screen on boot (when SDDM was supposed to show up). 

`~mhwd -li` output:

`> Installed PCI configs:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
    video-nvidia-440xx            2019.10.25               false            PCI`
